<center> <h1>Unit 2</h1> </center>
<center> <h1>Numpy, Pandas, Matplotlib</h1> </center>
<center>(Execute "Numpy, Pandas, and Matplotlib.ipynb" along)</center>
<br>
<br>
<br>
<center> <h3>IST 718 – Big Data Analytics</h3> </center>
<center> <h3>Daniel E. Acuna</h3> </center>
<center> <h3>http://acuna.io</h3> </center>

# The Scientific Python Ecosystem
- The following commonly-used Python modules are a part of an ecosystem referred to as ***SciPy***:  

<center><img src="./images/unit-02/unit-02-0_pfds5.png" width="90%" align="center"></center>

# Python Modules and Packages
- A ***module*** is single Python file that is intended to be imported into other Python scripts.
  - The Python Standard Library is the standard foundation of the language and does not need to be imported into a Python script.
  - Other reusable code is imported as modules.
  
  
- A ***package*** is a collection of Python modules under a common namespace.
  - Think of packages as folders, and modules as files in a folder.

# Numpy

- Vanilla Python lists do not do some of the standard linear algebra


In [ ]:
A = [1, 2, 3, 4]
4*A

# Numpy (2)

- Numpy stores multi-dimensional arrays and allows to make linear computations very efficiently

In [2]:
import numpy as np

# Creating arrays

- You can create arrays in two ways
  - From a Python list or tuple
  - From a special matrix generator
  - Other libraries generate Numpy arrays

In [3]:
print("From vanilla Python", np.array([1,2,3,4]))
print("From generators", np.zeros((3, 3)))

From vanilla Python [1 2 3 4]
From generators [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# ND-arrays store only one data type
- For efficiency reasons, an array only stores one datatype

In [4]:
A0 = np.array([0, 2, "cat"])
print(A0)
print(A0.dtype)

['0' '2' 'cat']
<U21


# Accessing elements

- You access individual elements with `A[i]` syntax
- Slices with `A[start:stop:step]`
- In multiple dimensions: `A[i, j]` or `A[start:stop:step, start:stop:step]`

In [6]:
# some examples
A1 = np.array([1, 2, 3, 4])
A2 = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])

In [7]:
print('A1[0] => ', A1[0])
print('A1[0:3:2] =>', A1[0:3:2])

A1[0] =>  1
A1[0:3:2] => [1 3]


In [8]:
print('A2[0] =>', A2[0])
print('A2[0:3:2] =>', A2[0:3:2])

A2[0] => [1 2 3]
A2[0:3:2] => [[1 2 3]
 [7 8 9]]


In [ ]:
print('A2[0:3:2, 0:2] =>', A2[0:3:2, 0:2])

# Matrix operations

- Standard linear algebra operations work in Numpy
- Scalar times matrix
- Matrix times matrix
- Operations such as inverse, transpose

In [9]:
# some operations are in another package
import numpy.linalg as la

A = np.array([[2, 3],
             [3, 4],
             [5, 6]])
B = np.array([[1, 2, 3],
             [4, 5, 6]])
C = np.array([[1, 3],
             [3, 2],
             [-1, 6]])

In [34]:
#Exercise

X = np.array([[1,20,0],[1,25,1],[1,33,1],[1,30,1]])
y = np.array([[30000],[34000],[33000],[40000]])

In [36]:
X

array([[ 1, 20,  0],
       [ 1, 25,  1],
       [ 1, 33,  1],
       [ 1, 30,  1]])

In [40]:
X.T.dot(X)

array([[   4,  108,    3],
       [ 108, 3014,   88],
       [   3,   88,    3]])

In [42]:
la.inv(X.T.dot(X)).dot(X.T).dot(y)

array([[2.97959184e+04],
       [1.02040816e+01],
       [5.57142857e+03]])

In [10]:
# Matrix transpose
A.T

array([[2, 3, 5],
       [3, 4, 6]])

In [12]:
2*A

array([[ 4,  6],
       [ 6,  8],
       [10, 12]])

In [16]:
4 + A

array([[ 6,  7],
       [ 7,  8],
       [ 9, 10]])

In [18]:
# multiplication
D = A.dot(B)
A.dot(B)

array([[14, 19, 24],
       [19, 26, 33],
       [29, 40, 51]])

In [19]:
# to the proper division we need to do A*C^-1
A.dot(np.invert(B))

array([[-19, -24, -29],
       [-26, -33, -40],
       [-40, -51, -62]])

In [20]:
# checking some identities it should be similar to D
la.inv(la.inv(D))

array([[17.51557093, 23.816609  , 30.11764706],
       [23.83391003, 32.62283737, 41.41176471],
       [36.47058824, 50.23529412, 64.        ]])

# Random number generation

- Sometimes it is important to generate random numbers to do simulations

In [21]:
# there are many random number generators
list(filter(lambda x: '_' not in x, dir(np.random)))

['BitGenerator',
 'Generator',
 'MT19937',
 'PCG64',
 'Philox',
 'RandomState',
 'SFC64',
 'SeedSequence',
 'beta',
 'binomial',
 'bytes',
 'chisquare',
 'choice',
 'dirichlet',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'gumbel',
 'hypergeometric',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'normal',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'rand',
 'randint',
 'randn',
 'random',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'shuffle',
 'test',
 'triangular',
 'uniform',
 'vonmises',
 'wald',
 'weibull',
 'zipf']

In [22]:
# generate 5 by 5 matrix with uniform numbers from 0 to 1
np.random.random(size=(5, 5))

array([[0.88316338, 0.16123073, 0.99399241, 0.8165291 , 0.64441612],
       [0.66654564, 0.41647477, 0.48980219, 0.78126532, 0.52500835],
       [0.27078596, 0.05744206, 0.24587313, 0.20821172, 0.19436906],
       [0.20546511, 0.90585564, 0.17749723, 0.69314198, 0.72758937],
       [0.09776279, 0.58315793, 0.08434956, 0.84551442, 0.17149792]])

In [23]:
# generate 5 by 5 matrix with normal (Gaussian) distribution
# mean 5 and standard deviation 2.
np.random.normal(size=(5, 5), loc=5., scale=2.)

array([[9.46056642, 6.38304394, 2.47493261, 1.46910171, 8.76425348],
       [6.93713253, 7.38397293, 2.56292269, 5.93787372, 8.0557712 ],
       [5.64063157, 5.10061878, 5.16871559, 1.98021585, 6.66504327],
       [6.07300602, 3.19464628, 7.59088956, 6.0031186 , 6.15849512],
       [3.57804303, 3.44178092, 2.94211098, 3.23449065, 2.11426699]])

# Aggregate operations

- There could be several summary operations that we could do across one dimension or several dimensions
- For example, the average per row or column

In [43]:
A3 = np.random.random(size=(3, 5))

In [26]:
# mean across all dimension
A3.mean()

0.422908266652617

In [27]:
# mean across rows (dimension 0)
A3.mean(axis=0)

array([0.1006235 , 0.79500395, 0.23721196, 0.40492128, 0.57678064])

In [28]:
# mean across columns (dimension 1)
A3.mean(axis=1)

array([0.4784123 , 0.41092776, 0.37938474])

In [29]:
# there are mamy such operations
list(filter(lambda x: '_' not in x, dir(A3)))

['T',
 'all',
 'any',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'astype',
 'base',
 'byteswap',
 'choose',
 'clip',
 'compress',
 'conj',
 'conjugate',
 'copy',
 'ctypes',
 'cumprod',
 'cumsum',
 'data',
 'diagonal',
 'dot',
 'dtype',
 'dump',
 'dumps',
 'fill',
 'flags',
 'flat',
 'flatten',
 'getfield',
 'imag',
 'item',
 'itemset',
 'itemsize',
 'max',
 'mean',
 'min',
 'nbytes',
 'ndim',
 'newbyteorder',
 'nonzero',
 'partition',
 'prod',
 'ptp',
 'put',
 'ravel',
 'real',
 'repeat',
 'reshape',
 'resize',
 'round',
 'searchsorted',
 'setfield',
 'setflags',
 'shape',
 'size',
 'sort',
 'squeeze',
 'std',
 'strides',
 'sum',
 'swapaxes',
 'take',
 'tobytes',
 'tofile',
 'tolist',
 'tostring',
 'trace',
 'transpose',
 'var',
 'view']

# Chaining operations

- Because each Numpy operations returns an array, we can easily chain operations

In [46]:
A4 = np.random.random(size=(3, 5))

In [47]:
A4.T.mean(axis=0).sum()

1.1798287971354773

# Selecting elements with "masks"

In [48]:
# we can create boolean masks
A4 > 0.5

array([[False, False, False,  True,  True],
       [False, False, False,  True,  True],
       [False, False, False, False, False]])

In [52]:
# and then use those broadcast operations to get the values
A4[A4>0.5]

array([0.71489299, 0.78946061, 0.67460378, 0.87564654])

In [53]:
# you can also select entire rows using the same idea
A4.sum(axis=1)>2.5

array([False, False, False])

In [54]:
# select rows
A4[A4.sum(axis=1)>2.5]

array([], shape=(0, 5), dtype=float64)

# Operation broadcasting

- Sometimes we might want to apply an operation to each row (or dimension)
- For example, subtract the mean row across a matrix
$$ A_{\text{centered}} = (a_{ij} - \sum_z a_{zj})_{ij}$$
- Or "standardize" columns
$$ A_{\text{standardized}} = (\frac{a_{ij} - \sum_z a_{zj}}{\text{std}(a_{:j})})_{ij}$$

In [ ]:
A5 = np.random.random(size=(5, 3))

In [ ]:
# centered
A5 - A5.mean(axis=0)

In [ ]:
# standardized
(A5 - A5.mean(axis=0))/A5.std(axis=0)

# Apply other functions to arrays
There are many functions that you can apply to arrays. In fact all functions that look convenient are a wrap to more explicit functions. For example, `A + 3` is a wrap around `np.add(A, 3)`

In [ ]:
A + 3

In [ ]:
np.add(A, 3)

In [ ]:
np.sin(A)

In [ ]:
# exponential

np.exp(A)

# Activity: Linear regression
- Linear regression is a simple linear prediction method
- $age = (30 \; 20\;  33\;  25\;  50)^T$
- $income = (25000\;  22000\;  21000\;  27000\;  40000)$
- Let's assume a simple model
$$ \hat{income} = b_0 + b_1 age $$
- Use $b = (20000 \; 5000)^T$
- Define the matrices X, y, and b for the predictions $Xb$

In [ ]:
# define X
# lets define simple model for making predictions
# define X, y, and b

# Activity: Compute the Mean Squared Error
- Sometimes, we want to compute the mean squared error of a model
$$MSE(b) = \frac{1}{n}\sum_{i=1}^{n} (\hat{income}_i - income_i)^2$$
- Write a function `mse` that takes X, b, and y, and computes MSE

In [5]:
def mse(X, b, y):
    pass

# Activity: Computing the gradient of MSE
$$\Delta MSE = (\frac{d MSE(b_0)}{db_0} \quad \frac{d MSE(b_1)}{db_1})^T$$
- Define a function `grad` that takes X and b and returns the gradient of MSE

In [3]:
def grad(X, b):
    pass

# Activity: Gradient descent

- The following algorithm finds the $b$ that minimizes MSE

b = random vector
for i in [1, ..., n]:
    b = b - L grad(X, b)

- where L is known as the learning rate.
- Display the `mse` after each iteration. The `mse` should decrease after each iteration

In [2]:
b = random vector
for i in [1, ..., n]:
    b = b - L grad(X, b)

SyntaxError: invalid syntax (<ipython-input-2-59617efdd8c7>, line 1)

In [ ]:
# Pandas

- One of the problems with numpy arrays is that the columns and rows do not have names
- Also Numpy arrays can hold only one dataset
- Sometimes, we want to store something like a "spreadsheet" with names for columns and different datatypes

# What is pandas?
- ***pandas*** is an open-source library with easy-to-use data structures and functions that simplifies data analysis and modeling in Python, including:
  - `DataFrame` and `Series` data structures
  - tools for reading and writing data in CSV format, Excel, and SQL databases
  - "group by" operator on data sets
  - merging and joining data sets  


- pandas data structures are used in many other Python libraries, so it is a good library to be familiar with.

# Using Pandas in Your Programs
- We’ll need to import some packages and modules to use Pandas
```python
import pandas as pd
import numpy as np
from pandas import DataFrame, Series
```

# Essential Pandas: Series and DataFrames
- Pandas has two data structures
  - `Series` $\rightarrow$ A Labeled list of data, 
  - `DataFrame` $\rightarrow$ A dictionary of `Series`
  

- The `DataFrame` is a table of data, and the `Series` represents one column in that table.


- NOTE: Pandas is “smart enough” to create a `DataFrame` from a list of dictionary, too.

# Demo: Exploring Pandas DataFrame and Series

# Demo: Pandas Data Manipulations
<h3><font color="gray">Row and Column Extractions</font></h3>

# Loading From a File to Pandas is Easy
- Use the `read_csv` pandas method to load data.
- It assumes first row is a header, but it can be manually overridden.
- http://pandas.pydata.org/pandas-docs/stable/io.html

# Demo: Exploring a data set in pandas

# matplotlib
- A 2D and 3D plotting library that can be used by Python as well as other frameworks.
- Has a large API with functions that can graph just about any plot imaginable.
<center><img src="./images/unit-02/unit-02-0_pfds6.png" width="60%" align="center"></center>

# matplotlib
<br>
<div class="container2">
  <div class="row2">
    <div class="col-6">
        <ul>
  <li>A 2D and 3D plotting library that can be used by Python as well as other frameworks.</li>
  <br>           
  <li>Has a large API with functions that can graph just about any plot imaginable.</li>
</ul>
      </div>
    <div class="col-6">
        <ul>
  <center><img src="./images/unit-02/unit-02-0_pfds6.png" width="100%" align="center"></center>
</ul>

    </div>
  </div>
</div>